force-app/main/default/objects/TestAccountName__c/TestAccountName__c.object-meta.xml
<CustomObject>
    <label>TestAccountName</label>
    <nameField>
        <label>TestAccountName Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestAccountNames</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestAccountNameHistory__c/TestAccountNameHistory__c.object-meta.xml
<CustomObject>
    <label>TestAccountNameHistory</label>
    <nameField>
        <label>TestAccountNameHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestAccountNameHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestAccountNameHistory__c/fields/TestAccountNameId__c.field-meta.xml
<CustomField>
    <fullName>TestAccountNameId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TestAccountName</label>
    <referenceTo>TestAccountName__c</referenceTo>
    <relationshipLabel>TestAccountNameHistories</relationshipLabel>
    <relationshipName>TestAccountNameHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchChangeTestAccountHistoryName.cls
public class BatchChangeTestAccountHistoryName implements Database.Batchable<sObject> {
    List<Id> TestAccountNameIds;
    
    public BatchChangeTestAccountHistoryName (List<Id> TestAccountNameIds){
        this.TestAccountNameIds=TestAccountNameIds;
    }

    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Name, (SELECT Name FROM TestAccountNameHistories__r) FROM TestAccountName__c WHERE Id in:' + TestAccountNameIds;
        return Database.getQueryLocator(query);
    }


    public void execute(Database.BatchableContext bc, List<TestAccountName__c> scope){
        List<TestAccountNameHistory__c> historiesToUpdate = new List<TestAccountNameHistory__c>();
            for(TestAccountName__c test : scope){
                for (TestAccountNameHistory__c history : test.TestAccountNameHistories__r) {
                    history.Name=test.Name+' History';
                    historiesToUpdate.add(history);
                }
            }
        update historiesToUpdate; 
    }


    public void finish(Database.BatchableContext bc){}
}