force-app/main/default/objects/TestAccountName__c/TestAccountName__c.object-meta.xml
<CustomObject>
    <label>TestAccountName</label>
    <nameField>
        <label>TestAccountName Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestAccountNames</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestAccountName__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TestAccountNames</relationshipLabel>
    <relationshipName>TestAccountNames</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestAccountName__c/fields/DeletedAccountId__c.field-meta.xml
<CustomField>
    <fullName>DeletedAccountId__c</fullName>
    <label>DeleteAccountId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestAccountName__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>active</fullName>
                <default>true</default>
                <label>active</label>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
            <value>
                <fullName>updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAccountNameTriggerHandler.cls
public with sharing class TestAccountNameTriggerHandler extends TriggerHandler {
    private List<Account> newAccountList;
    private Map<Id, Account> oldAccountMap;
    private Map<Id, Account> newAccountMap;

    public TestAccountNameTriggerHandler() {
        newAccountList = (List<Account>) Trigger.NEW;
        oldAccountMap  = (Map<Id, Account>) Trigger.oldMap;
        newAccountMap  = (Map<Id, Account>) Trigger.newMap;
    }


    public override void  afterInsert() {
        List<TestAccountName__c> testsToInsert = new List<TestAccountName__c>();
        for (Account a : newAccountList) {
            TestAccountName__c test = new TestAccountName__c(Name = a.Name);
            test.AccountId__c = a.Id;
            testsToInsert.add(test);
        }
        insert(testsToInsert);
    }


    public override void afterUpdate() {
        List<TestAccountName__c> testsToUpdate = new List<TestAccountName__c>();
        Set<Id> accountIds = new Set<Id>();
        for (Account a : newAccountList) {
            if (a.Name != oldAccountMap.get(a.Id).Name) {
                accountIds.add(a.Id);
            }
        }
        for (TestAccountName__c test : [SELECT Name, Status__c, AccountId__c
                                        FROM TestAccountName__c
                                        WHERE AccountId__c IN :accountIds]) {
            test.Name = newAccountMap.get(test.AccountId__c).Name;
            test.Status__c = Constants.UPDATED;
            testsToUpdate.add(test);
        }
        if (testsToUpdate.size() > 0) {
            update testsToUpdate;
        }
    }

    
    public override void afterDelete() {
        List<TestAccountName__c> testsToChangeStatus = new List<TestAccountName__c>();
        Set<Id> accountIds = oldAccountMap.keySet();
        for (TestAccountName__c test : [SELECT Status__c
                                        FROM TestAccountName__c
                                        WHERE DeletedAccountId__c IN :accountIds]) {
            test.Status__c = Constants.DELETED;
            testsToChangeStatus.add(test);
        }
        update testsToChangeStatus;
    }
}