force-app/main/default/objects/TestAccountName__c/TestAccountName__c.object-meta.xml
<CustomObject>
    <label>TestAccountName</label>
    <nameField>
        <label>TestAccountName Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestAccountNames</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestAccountName__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>active</fullName>
                <default>true</default>
                <label>active</label>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
            <value>
                <fullName>updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TestAccountNameHistory__c/TestAccountNameHistory__c.object-meta.xml
<CustomObject>
    <label>TestAccountNameHistory</label>
    <nameField>
        <label>TestAccountNameHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestAccountNameHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestAccountNameHistory__c/fields/TestAccountNameId__c.field-meta.xml
<CustomField>
    <fullName>TestAccountNameId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TestAccountName</label>
    <referenceTo>TestAccountName__c</referenceTo>
    <relationshipLabel>TestAccountNameHistories</relationshipLabel>
    <relationshipName>TestAccountNameHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestAccountNameHistoryTriggerHandler.cls
public with sharing class TestAccountNameHistoryTriggerHandler extends TriggerHandler {
    private List<TestAccountName__c> newAccountList;
    private Map<Id, TestAccountName__c> oldAccountMap;

    public TestAccountNameHistoryTriggerHandler() {
        newAccountList = (List<TestAccountName__c>) Trigger.NEW;
        oldAccountMap  = (Map<Id, TestAccountName__c>) Trigger.oldMap;
    }


    public override void  afterInsert () {
        List<TestAccountNameHistory__c> historiesToInsert = new List<TestAccountNameHistory__c>();
        for (TestAccountName__c test : newAccountList) {
            TestAccountNameHistory__c history = new TestAccountNameHistory__c(Name = test.Name + ' History');
            history.TestAccountNameId__c = test.Id;
            history.Description__c = 'New TestAccountName Object with Id \'' + test.Id + '\' and name \''
                                     + test.Name + '\' was created. Status is \'' + test.Status__c + '\'';
            historiesToInsert.add(history);
        }
        insert historiesToInsert;
    }

    
    public override void afterUpdate() {
        List<TestAccountNameHistory__c> historiesToInsert = new List<TestAccountNameHistory__c>();
        Set <Id> ids = new Set<Id>();
        for (TestAccountName__c test : newAccountList) {
            TestAccountNameHistory__c history = new TestAccountNameHistory__c(Name = test.Name + ' History');
            history.Description__c = 'TestAccountName Object with Id \''
                                     + test.Id + '\' and name \''
                                     + test.Name + '\' was changed. Status is \''
                                     + test.Status__c + '\'';
            history.TestAccountNameId__c = test.Id;
            historiesToInsert.add(history);
            if (test.Name != oldAccountMap.get(test.Id).Name) {
                ids.add(test.Id);
            }
        }
        insert historiesToInsert;
        if (ids.size() > 0) {
            BatchChangeTestAccountHistoryName myBatchObject = new BatchChangeTestAccountHistoryName(ids);
            ID batchprocessid = Database.executeBatch(myBatchObject);
        }
    }
}