force-app/main/default/objects/TestAccountNameHistory__c/TestAccountNameHistory__c.object-meta.xml
<CustomObject>
    <label>TestAccountNameHistory</label>
    <nameField>
        <label>TestAccountNameHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestAccountNameHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestAccountNameHistory__c/fields/TestAccountNameId__c.field-meta.xml
<CustomField>
    <fullName>TestAccountNameId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TestAccountName</label>
    <referenceTo>TestAccountName__c</referenceTo>
    <relationshipLabel>TestAccountNameHistories</relationshipLabel>
    <relationshipName>TestAccountNameHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchDeleteHistories.cls
public class BatchDeleteHistories implements Database.Batchable<sObject> {
    
    Id i;
    
    public BatchDeleteHistories(Id i) {
        this.i=i;
    }

    public List<TestAccountNameHistory__c> start(Database.BatchableContext bc) {
        return [SELECT Id FROM TestAccountNameHistory__c WHERE TestAccountNameId__c=:i];
    }


    public void execute(Database.BatchableContext bc, List<TestAccountNameHistory__c> scope) {
        delete scope;  
    }


    public void finish(Database.BatchableContext bc) {}
}